### ISSUE TITLE
Short flag "f" used twice and results in an error

### ISSUE THREAD

**Issue by camoa** [rlnorthcutt/sitemapExport#1]
> go build
go: downloading github.com/spf13/cobra v1.8.1
go: downloading github.com/JohannesKaufmann/html-to-markdown v1.6.0
go: downloading github.com/schollz/progressbar/v3 v3.16.0
go: downloading github.com/PuerkitoBio/goquery v1.10.0
go: downloading github.com/kennygrant/sanitize v1.2.4
go: downloading github.com/jung-kurt/gofpdf v1.16.2
go: downloading golang.org/x/net v0.29.0
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/andybalholm/cascadia v1.3.2
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading github.com/mitchellh/colorstring v0.0.0-20190213212951-d06e56a500db
go: downloading golang.org/x/term v0.24.0
go: downloading github.com/rivo/uniseg v0.4.7
go: downloading golang.org/x/sys v0.25.0
> ls
crawler  feed  formatter  go.mod  go.sum  html2text  LICENSE  main.go  README.md  sitemapExport  writer
> ./sitemapExport
panic: unable to redefine 'f' shorthand in "sitemapExport" flagset: it's already used for "filename" flag

goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).AddFlag(0xc0001ac400, 0xc0001cbb80)
	/home/camoa/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:874 +0x3f5
github.com/spf13/pflag.(*FlagSet).VarPF(0xc0001ac400, {0x9b19f0, 0xcc4350}, {0x8e062c, 0x6}, {0x9a9520, 0x1}, {0x8fa60f, 0x2d})
	/home/camoa/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:831 +0x105
github.com/spf13/pflag.(*FlagSet).VarP(...)
	/home/camoa/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:837
github.com/spf13/pflag.(*FlagSet).StringVarP(0xc0000dbe10?, 0x6af585?, {0x8e062c?, 0x4d14e0?}, {0x9a9520?, 0x75ba8d?}, {0x8dea36?, 0x8?}, {0x8fa60f, 0x2d})
	/home/camoa/go/pkg/mod/github.com/spf13/pflag@v1.0.5/string.go:42 +0x69
main.init.0()
	/home/camoa/workspace/sitemapExport/main.go:43 +0x1ab

Any recommendations?

**Comment by camoa** [comment]
Hack the code and changed the filename flag, from f to n

**Comment by rlnorthcutt** [comment]
Nice catch, @camoa! I've fixed it.
